# Generated by Django 6.0.1 on 2026-03-14 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ligne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_ligne', models.CharField(max_length=50, unique=True)),
                ('point_depart', models.CharField(max_length=100)),
                ('point_arrivee', models.CharField(max_length=100)),
                ('duree_estimee', models.DurationField(help_text='الوقت التقريبي للرحلة')),
            ],
        ),
        migrations.CreateModel(
            name='Horaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_depart', models.TimeField()),
                ('heure_arrivee', models.TimeField()),
                ('frequence', models.CharField(help_text='مثال: يوميا، أيام الأسبوع فقط', max_length=50)),
                ('bus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.bus')),
                ('ligne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.ligne')),
            ],
        ),
    ]
